name: portfolio
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter 
  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.1.2
  font_awesome_flutter: ^10.5.0
  carousel_slider: ^4.2.1
  animated_text_kit: ^4.2.2
  rive: ^0.11.16
  localization: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/core/i18n/
    - assets/rive/logo.riv
  
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700

